### PR TITLE
Handle TIFFs without embedded previews

### LINKED ISSUE #39: Preview of TIFFs without embedded preview
This line

https://github.com/ariselseng/camerarawpreviews/blob/0a8268aaddd6445be4f833638b42e834156af30a/lib/AppInfo/Application.php#L64

registers a wrong MIME type for .tif files (no .tiff files, tho) so that your `RawPreview` class can handle TIFF previews. Currently `RawPreview` can only handle TIFFs with embedded previews. `OC\Preview\TIFF` can also preview TIFF files that do not include a preview (like these [test-tiffs.zip](https://github.com/ariselseng/camerarawpreviews/files/4016867/test-tiffs.zip) )

exiftool returns this for the example file:
```shell
./exiftool -json -preview:all t/XING_T24.tiff 
[{
  "SourceFile": "t/XING_T24.tiff"
}]
```

Could you maybe add a check that sees if the Nextcloud instance has `OC\Preview\TIFF` configured for a preview provider and if that's the case skip the MIME type registration of `tif` to `image/x-dcraw`?
Alternatively one could probably teach this app to fall back to extracting a preview form the `SourceFile` TIFF when the `imagick` PHP extension is present and exiftool does not return a `PreviewTIFF` key. 

see nextcloud/server#12876

### PR DESCRIPTION
**Pull request by d--j**
When imagick extension with TIFF support is found also handle TIFF files without embedded previews by generating a preview from the whole file.

closes #39

Can also handle multipage TIFFs without embedded preview (first page gets previewed)

### CODE REVIEW

File: lib/RawPreview.php [hunk 1]
```diff
@@ -118,21 +122,30 @@ protected function getResizedPreview($tmpPath, $maxX, $maxY)
...
         $im = Image::make($previewImageTmpPath);
         $im->orientate();
         $im->resize($maxX, $maxY, function ($constraint) {
             $constraint->aspectRatio();
             $constraint->upsize();
         });
-        unlink($previewImageTmpPath);
+	    if ($previewTag !== 'SourceTIFF') {
+		    unlink( $previewImageTmpPath );
+	    }
```
Comment (ariselseng) [inline lib/RawPreview.php]: Fix indention here and this can be merged :)

**Comment by ariselseng** [comment]
@d--j This looks like it will work well. Thank you for the PR!

File: lib/RawPreview.php (hunk 1 above)
Comment (d--j) [reply lib/RawPreview.php]: sorry, my IDE did too much "smart" stuff. should be consistent now.
